name: init-npm-repo
description: "Checkout and install dependencies for an npm project"
inputs:
  node-version:
    description: "Node.js version to use"
    required: true
runs:
  using: composite
  steps: 
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      run: npm install
      shell: bash
