name: build-test-deploy
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: nathaniel-palmer-simplisafe/actions-learning-pathway/.github/actions/init-npm-repo@main
        with:
          node-version: '18.x' 
      - run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: nathaniel-palmer-simplisafe/actions-learning-pathway/.github/actions/init-npm-repo@main
        with:
          node-version: '18.x' 
      - run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      deployments: write
      contents: write
      statuses: write
      actions: write
      pages: write     
      id-token: write
    steps:
      - uses: nathaniel-palmer-simplisafe/actions-learning-pathway/.github/actions/init-npm-repo@main
        with:
          node-version: '18.x' 
      - run: npm run build
      - name: configure github pages
        uses: actions/configure-pages@v3    
        with:
          static_site_generator: next
      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./out"
      - name: deploy
        id: deploy
        uses: actions/deploy-pages@v1
